sudo: required
os: linux

before_install:
- sudo apt-get update -qq

script:
- chmod +x tests/*.sh
- chmod +x scripts/*.sh

# little hack for unittesting
- cd scripts
- ln -s ../tests/test_clean.sh   test_clean.sh
- ln -s ../tests/test_install.sh test_install.sh
- ln -s ../tests/test_main.sh    test_main.sh
- bash test_main.sh

notifications:
  email: false
  
